remote:
  real:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/threemc
  
  fertility:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/fertility

fields:
  requester:
    required: false
  author:
    required: false

# vault:
#   addr: https://vault.dide.ic.ac.uk:8200

global_resources:
  global
